name: Update IPs

on:
  schedule:
    - cron: "0 2 * * *"  # Ejecutar diariamente a las 2:00 AM (UTC)

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch IPs from API
        env:
          API_URL: "https://my.imperva.com/api/integration/v1/ips"
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          import requests
          import json

          response = requests.get(API_URL, headers={"Authorization": f"Bearer {API_TOKEN}"})
          ips_nuevas = response.json()
          
          with open("lista_ips.json", "w") as file:
              json.dump(ips_nuevas, file, indent=2)

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add lista_ips.json
          git commit -m "Actualizar lista de IPs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
